from graph.state import SOCState


def report_generator(state: SOCState) -> SOCState:

    investigation = state["investigation_result"]
    intel = state["threat_intelligence"]

    report = f"""
==================================================
            SentinelAI Incident Report
==================================================

Attack Summary
--------------
{investigation["attack_summary"]}

Attack Type
-----------
{investigation["attack_type"]}

Severity
--------
{state["severity"]}

Confidence
----------
{investigation["confidence"]}%

Reasoning
---------
{investigation["reasoning"]}

Threat Intelligence
-------------------
Reputation : {intel["reputation"]}
Country    : {intel["country"]}
Malicious Score : {intel["malicious_score"]}

MITRE ATT&CK
------------
{chr(10).join(investigation["mitre_attack"])}

Recommended Actions
-------------------
{chr(10).join(state["recommended_action"])}

Next Investigation Steps
------------------------
{chr(10).join(investigation["next_steps"])}

==================================================
Generated by SentinelAI
==================================================
"""

    state["incident_report"] = report

    print("Report Generated")

    return state